import type { Metadata } from "next";
import { Manrope } from "next/font/google";
import "./globals.css";
import Wrapper from "./components/Wrapper";
import Footer from "./components/Footer";
import Header from "./components/Header";
import { ConvexClientProvider } from "@/provider/convexProvider";
import { CartProvider } from "@/context/cartContext";
import { ConvexProviderWrapper } from "@/lib/covexClient";

const manrope = Manrope({
  subsets: ["latin"],
  variable: "--font-manrope",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={` ${manrope.variable} antialiased`}>
        <ConvexProviderWrapper>
          <CartProvider>
            <Wrapper className="bg-black px-0">
              <Header />
            </Wrapper>
            {children}
            <Wrapper className="bg-black mt-10">
              <Footer />
            </Wrapper>
          </CartProvider>
        </ConvexProviderWrapper>
      </body>
    </html>
  );
}
